type chainparams
type feature_set
type bitcoin_txid
type u16
type amount_sat
type u32
type channel_config
type fee_states
type bitcoin_signature
type per_peer_state
type pubkey
type basepoints
type u8
type amount_msat
type node_id
type bool
type changed_htlc
type u64
type existing_htlc
type short_channel_id
type secret
type secp256k1_ecdsa_signature
type penalty_base
type sha256
type wirestring
type fulfilled_htlc
type failed_htlc
type added_htlc
type bitcoin_tx
type onionmsg_path

message 1000 @channel_init:
  chainparams @chainparams
  feature_set @our_features
  bitcoin_txid @funding_txid
  u16 @funding_txout
  amount_sat @funding_satoshi
  u32 @minimum_depth
  channel_config @our_config
  channel_config @their_config
  fee_states @fee_states
  u32 @feerate_min
  u32 @feerate_max
  u32 @feerate_penalty
  bitcoin_signature @first_commit_sig
  per_peer_state @per_peer_state
  pubkey @remote_fundingkey
  basepoints @remote_basepoints
  pubkey @remote_per_commit
  pubkey @old_remote_per_commit
  side(enum) @opener
  u32 @fee_base
  u32 @fee_proportional
  amount_msat @local_msatoshi
  basepoints @our_basepoints
  pubkey @our_funding_pubkey
  node_id @local_node_id
  node_id @remote_node_id
  u32 @commit_msec
  u16 @cltv_delta
  bool @last_was_revoke
  u16 @num_last_sent_commit
  changed_htlc*&num_last_sent_commit @last_sent_commit
  u64 @next_index_local
  u64 @next_index_remote
  u64 @revocations_received
  u64 @next_htlc_id
  u16 @num_existing_htlcs
  existing_htlc*&num_existing_htlcs @htlcs
  bool @local_funding_locked
  bool @remote_funding_locked
  short_channel_id @funding_short_id
  bool @reestablish
  bool @send_shutdown
  bool @remote_shutdown_received
  u16 @final_scriptpubkey_len
  u8*&final_scriptpubkey_len @final_scriptpubkey
  u8 @flags
  u16 @init_peer_pkt_len
  u8*&init_peer_pkt_len @init_peer_pkt
  bool @reached_announce_depth
  secret @last_remote_secret
  u16 @flen
  u8*&flen @their_features
  u16 @upfront_shutdown_script_len
  u8*&upfront_shutdown_script_len @upfront_shutdown_script
  secp256k1_ecdsa_signature? @remote_ann_node_sig
  secp256k1_ecdsa_signature? @remote_ann_bitcoin_sig
  bool @option_static_remotekey
  bool @dev_fast_gossip
  bool @dev_fail_process_onionpacket
  u32 @num_penalty_bases
  penalty_base*&num_penalty_bases @pbases

message 1002 @channel_funding_depth:
  short_channel_id? @short_channel_id
  u32 @depth

message 1004 @channel_offer_htlc:
  amount_msat @amount_msat
  u32 @cltv_expiry
  sha256 @payment_hash
  u8*1366 @onion_routing_packet
  pubkey? @blinding

message 1104 @channel_offer_htlc_reply:
  u64 @id
  u16 @len
  u8*&len @failuremsg
  wirestring @failurestr

message 1005 @channel_fulfill_htlc:
  fulfilled_htlc @fulfilled_htlc

message 1006 @channel_fail_htlc:
  failed_htlc @failed_htlc

message 1019 @channel_got_funding_locked:
  pubkey @next_per_commit_point

message 1020 @channel_sending_commitsig:
  u64 @commitnum
  penalty_base? @pbase
  fee_states @fee_states
  u16 @num_changed
  changed_htlc*&num_changed @changed
  bitcoin_signature @commit_sig
  u16 @num_htlc_sigs
  secp256k1_ecdsa_signature*&num_htlc_sigs @htlc_sigs

message 1120 @channel_sending_commitsig_reply:

message 1021 @channel_got_commitsig:
  u64 @commitnum
  fee_states @fee_states
  bitcoin_signature @signature
  u16 @num_htlcs
  secp256k1_ecdsa_signature*&num_htlcs @htlc_signature
  u16 @num_added
  added_htlc*&num_added @added
  u16 @num_fulfilled
  fulfilled_htlc*&num_fulfilled @fulfilled
  u16 @num_failed
  failed_htlc*&num_failed @failed
  u16 @num_changed
  changed_htlc*&num_changed @changed
  bitcoin_tx @tx

message 1121 @channel_got_commitsig_reply:

message 1022 @channel_got_revoke:
  u64 @revokenum
  secret @per_commitment_secret
  pubkey @next_per_commit_point
  fee_states @fee_states
  u16 @num_changed
  changed_htlc*&num_changed @changed
  penalty_base? @pbase
  bitcoin_tx? @penalty_tx

message 1122 @channel_got_revoke_reply:

message 1023 @channel_send_shutdown:
  u16 @shutdown_len
  u8*&shutdown_len @shutdown_scriptpubkey

message 1024 @channel_got_shutdown:
  u16 @scriptpubkey_len
  u8*&scriptpubkey_len @scriptpubkey

message 1025 @channel_shutdown_complete:
  per_peer_state @per_peer_state

message 1026 @channel_dev_reenable_commit:

message 1126 @channel_dev_reenable_commit_reply:

message 1027 @channel_feerates:
  u32 @feerate
  u32 @min_feerate
  u32 @max_feerate
  u32 @penalty_feerate

message 1033 @channel_dev_memleak:

message 1133 @channel_dev_memleak_reply:
  bool @leak

message 1028 @channel_fail_fallen_behind:
  pubkey? @remote_per_commitment_point

message 1029 @channel_specific_feerates:
  u32 @feerate_base
  u32 @feerate_ppm

message 1017 @channel_got_announcement:
  secp256k1_ecdsa_signature @remote_ann_node_sig
  secp256k1_ecdsa_signature @remote_ann_bitcoin_sig

message 1008 @channel_send_error:
  wirestring @reason

message 1108 @channel_send_error_reply:

message 1142 @got_onionmsg_to_us:
  pubkey? @reply_blinding
  u16 @reply_path_len
  onionmsg_path*&reply_path_len @reply_path

message 1143 @got_onionmsg_forward:
  short_channel_id? @next_scid
  node_id? @next_node_id
  pubkey? @next_blinding
  u8*1366 @next_onion

message 1040 @send_onionmsg:
  u8*1366 @onion
  pubkey? @blinding
