type chainparams
type feature_set
type node_id
type u16
type wireaddr_internal
type u8
type wireaddr
type bool
type wirestring
type u32
type errcode_t
type per_peer_state

message 2000 @connectctl_init:
  chainparams @chainparams
  feature_set @our_features
  node_id @id
  u16 @num_wireaddrs
  wireaddr_internal*&num_wireaddrs @wireaddrs
  addr_listen_announce(enum)*&num_wireaddrs @listen_announce
  wireaddr? @tor_proxyaddr
  bool @use_tor_proxy_always
  bool @dev_allow_localhost
  bool @use_dns
  wirestring @tor_password
  bool @use_v3_autotor

message 2100 @connectctl_init_reply:
  u16 @num_bindings
  wireaddr_internal*&num_bindings @bindings
  u16 @num_announcable
  wireaddr*&num_announcable @announcable

message 2025 @connectctl_activate:
  bool @listen

message 2125 @connectctl_activate_reply:

message 2112 @connect_reconnected:
  node_id @id

message 2001 @connectctl_connect_to_peer:
  node_id @id
  u32 @seconds_waited
  wireaddr_internal? @addrhint

message 2020 @connectctl_connect_failed:
  node_id @id
  errcode_t @failcode
  wirestring @failreason
  u32 @seconds_to_delay
  wireaddr_internal? @addrhint

message 2002 @connect_peer_connected:
  node_id @id
  wireaddr_internal @addr
  per_peer_state @pps
  u16 @flen
  u8*&flen @features

message 2015 @connectctl_peer_disconnected:
  node_id @id

message 2033 @connect_dev_memleak:

message 2133 @connect_dev_memleak_reply:
  bool @leak
