type node_id
type bool
type gossip_state
type u16
type wireaddr

message 4000 @gossip_new_peer:
  node_id @id
  bool @gossip_queries_feature
  bool @initial_routing_sync

message 4100 @gossip_new_peer_reply:
  bool @success
  gossip_state? @gs

message 4001 @gossip_get_addrs:
  node_id @id

message 4101 @gossip_get_addrs_reply:
  u16 @num
  wireaddr*&num @addrs
