type node_id
type wirestring
type u16
type u8
type bip32_key_version
type chainparams
type secret
type privkey
type secrets
type sha256
type ext_key
type u64
type basepoints
type pubkey
type amount_sat
type u32
type utxo
type bitcoin_tx
type secp256k1_ecdsa_signature
type bitcoin_tx_output
type secp256k1_ecdsa_recoverable_signature
type bitcoin_signature
type witscript
type bool

message 1000 @hsmstatus_client_bad_request:
  node_id @id
  wirestring @description
  u16 @len
  u8*&len @msg

message 11 @hsm_init:
  bip32_key_version @bip32_key_version
  chainparams @chainparams
  secret? @hsm_encryption_key
  privkey? @dev_force_privkey
  secret? @dev_force_bip32_seed
  secrets? @dev_force_channel_secrets
  sha256? @dev_force_channel_secrets_shaseed

message 111 @hsm_init_reply:
  node_id @node_id
  ext_key @bip32

message 9 @hsm_client_hsmfd:
  node_id @id
  u64 @dbid
  u64 @capabilities

message 109 @hsm_client_hsmfd_reply:

message 10 @hsm_get_channel_basepoints:
  node_id @peerid
  u64 @dbid

message 110 @hsm_get_channel_basepoints_reply:
  basepoints @basepoints
  pubkey @funding_pubkey

message 4 @hsm_sign_funding:
  amount_sat @satoshi_out
  amount_sat @change_out
  u32 @change_keyindex
  pubkey @our_pubkey
  pubkey @their_pubkey
  u16 @num_inputs
  utxo*&num_inputs @inputs

message 104 @hsm_sign_funding_reply:
  bitcoin_tx @tx

message 6 @hsm_node_announcement_sig_req:
  u16 @annlen
  u8*&annlen @announcement

message 106 @hsm_node_announcement_sig_reply:
  secp256k1_ecdsa_signature @signature

message 7 @hsm_sign_withdrawal:
  amount_sat @satoshi_out
  amount_sat @change_out
  u32 @change_keyindex
  u16 @num_outputs
  bitcoin_tx_output*&num_outputs @outputs
  u16 @num_inputs
  utxo*&num_inputs @inputs
  u32 @nlocktime

message 107 @hsm_sign_withdrawal_reply:
  bitcoin_tx @tx

message 8 @hsm_sign_invoice:
  u16 @len
  u8*&len @u5bytes
  u16 @hrplen
  u8*&hrplen @hrp

message 108 @hsm_sign_invoice_reply:
  secp256k1_ecdsa_recoverable_signature @sig

message 1 @hsm_ecdh_req:
  pubkey @point

message 100 @hsm_ecdh_resp:
  secret @ss

message 2 @hsm_cannouncement_sig_req:
  u16 @calen
  u8*&calen @ca

message 102 @hsm_cannouncement_sig_reply:
  secp256k1_ecdsa_signature @node_signature
  secp256k1_ecdsa_signature @bitcoin_signature

message 3 @hsm_cupdate_sig_req:
  u16 @culen
  u8*&culen @cu

message 103 @hsm_cupdate_sig_reply:
  u16 @culen
  u8*&culen @cu

message 5 @hsm_sign_commitment_tx:
  node_id @peer_id
  u64 @channel_dbid
  bitcoin_tx @tx
  pubkey @remote_funding_key
  amount_sat @funding_amount

message 105 @hsm_sign_commitment_tx_reply:
  bitcoin_signature @sig

message 12 @hsm_sign_delayed_payment_to_us:
  u64 @commit_num
  bitcoin_tx @tx
  u16 @wscript_len
  u8*&wscript_len @wscript
  amount_sat @input_amount

message 13 @hsm_sign_remote_htlc_to_us:
  pubkey @remote_per_commitment_point
  bitcoin_tx @tx
  u16 @wscript_len
  u8*&wscript_len @wscript
  amount_sat @input_amount

message 14 @hsm_sign_penalty_to_us:
  secret @revocation_secret
  bitcoin_tx @tx
  u16 @wscript_len
  u8*&wscript_len @wscript
  amount_sat @input_amount

message 16 @hsm_sign_local_htlc_tx:
  u64 @commit_num
  bitcoin_tx @tx
  u16 @wscript_len
  u8*&wscript_len @wscript
  amount_sat @input_amount

message 19 @hsm_sign_remote_commitment_tx:
  bitcoin_tx @tx
  pubkey @remote_funding_key
  amount_sat @funding_amount
  u16 @num_witscripts
  witscript*&num_witscripts @output_witscripts
  pubkey @remote_per_commit
  bool @option_static_remotekey

message 20 @hsm_sign_remote_htlc_tx:
  bitcoin_tx @tx
  u16 @len
  u8*&len @wscript
  amount_sat @amounts_satoshi
  pubkey @remote_per_commit_point

message 21 @hsm_sign_mutual_close_tx:
  bitcoin_tx @tx
  pubkey @remote_funding_key
  amount_sat @funding

message 112 @hsm_sign_tx_reply:
  bitcoin_signature @sig

message 18 @hsm_get_per_commitment_point:
  u64 @n

message 118 @hsm_get_per_commitment_point_reply:
  pubkey @per_commitment_point
  secret? @old_commitment_secret

message 33 @hsm_dev_memleak:

message 133 @hsm_dev_memleak_reply:
  bool @leak

message 22 @hsm_check_future_secret:
  u64 @n
  secret @commitment_secret

message 122 @hsm_check_future_secret_reply:
  bool @correct

message 23 @hsm_sign_message:
  u16 @len
  u8*&len @msg

message 123 @hsm_sign_message_reply:
  secp256k1_ecdsa_recoverable_signature @sig
