type chainparams
type feature_set
type channel_config
type u32
type amount_msat
type per_peer_state
type basepoints
type pubkey
type u16
type u8
type bool
type byte
type amount_sat
type wirestring
type bitcoin_tx
type penalty_base
type bitcoin_signature
type bitcoin_txid

message 6000 @opening_init:
  chainparams @chainparams
  feature_set @our_features
  channel_config @our_config
  u32 @max_to_self_delay
  amount_msat @min_effective_htlc_capacity_msat
  per_peer_state @pps
  basepoints @our_basepoints
  pubkey @our_funding_pubkey
  u32 @minimum_depth
  u32 @min_feerate
  u32 @max_feerate
  u16 @lfeatures_len
  u8*&lfeatures_len @lfeatures
  bool @option_static_remotekey
  u16 @len
  u8*&len @msg
  byte?*32 @dev_temporary_channel_id
  bool @dev_fast_gossip

message 6005 @opening_got_offer:
  amount_sat @funding_satoshis
  amount_msat @push_msat
  amount_sat @dust_limit_satoshis
  amount_msat @max_htlc_value_in_flight_msat
  amount_sat @channel_reserve_satoshis
  amount_msat @htlc_minimum_msat
  u32 @feerate_per_kw
  u16 @to_self_delay
  u16 @max_accepted_htlcs
  u8 @channel_flags
  u16 @shutdown_len
  u8*&shutdown_len @shutdown_scriptpubkey

message 6105 @opening_got_offer_reply:
  wirestring? @rejection
  u16 @shutdown_len
  u8?*&shutdown_len @our_shutdown_scriptpubkey

message 6101 @opening_funder_reply:
  channel_config @their_config
  bitcoin_tx @first_commit
  penalty_base? @pbase
  bitcoin_signature @first_commit_sig
  per_peer_state @pps
  pubkey @revocation_basepoint
  pubkey @payment_basepoint
  pubkey @htlc_basepoint
  pubkey @delayed_payment_basepoint
  pubkey @their_per_commit_point
  u32 @minimum_depth
  pubkey @remote_fundingkey
  bitcoin_txid @funding_txid
  u16 @funding_txout
  u32 @feerate_per_kw
  amount_sat @our_channel_reserve_satoshis
  u16 @shutdown_len
  u8*&shutdown_len @shutdown_scriptpubkey

message 6002 @opening_funder_start:
  amount_sat @funding_satoshis
  amount_msat @push_msat
  u16 @len_upfront
  u8*&len_upfront @upfront_shutdown_script
  u32 @feerate_per_kw
  u8 @channel_flags

message 6102 @opening_funder_start_reply:
  u8 @script_len
  u8*&script_len @scriptpubkey
  bool @upfront_shutdown_negotiated

message 6012 @opening_funder_complete:
  bitcoin_txid @funding_txid
  u16 @funding_txout

message 6013 @opening_funder_cancel:

message 6004 @opening_funder_failed:
  wirestring @reason

message 6003 @opening_fundee:
  channel_config @their_config
  bitcoin_tx @first_commit
  penalty_base? @pbase
  bitcoin_signature @first_commit_sig
  per_peer_state @pps
  pubkey @revocation_basepoint
  pubkey @payment_basepoint
  pubkey @htlc_basepoint
  pubkey @delayed_payment_basepoint
  pubkey @their_per_commit_point
  pubkey @remote_fundingkey
  bitcoin_txid @funding_txid
  u16 @funding_txout
  amount_sat @funding_satoshis
  amount_msat @push_msat
  u8 @channel_flags
  u32 @feerate_per_kw
  u16 @msglen
  u8*&msglen @funding_signed_msg
  amount_sat @our_channel_reserve_satoshis
  u16 @local_shutdown_len
  u8*&local_shutdown_len @local_shutdown_scriptpubkey
  u16 @remote_shutdown_len
  u8*&remote_shutdown_len @remote_shutdown_scriptpubkey

message 6033 @opening_dev_memleak:

message 6133 @opening_dev_memleak_reply:
  bool @leak
