type channel_id
type wirestring
type bool
type per_peer_state
type u16
type u8

message 0xFFF4 @status_peer_error:
  channel_id @channel
  wirestring @desc
  bool @soft_error
  per_peer_state @pps
  u16 @len
  u8*&len @error_for_them
